@MyRecieBook.API_HostAddress = http://localhost:5101

### Testar a criação de usuário
POST {{MyRecieBook.API_HostAddress}}/api/User
Content-Type: application/json

{
  "nome": "Gabriel",
  "email": "gabriel@email.com"
}